%run after analysis_step1_process_ET_data_calls_and_fixes.m and depends on
%the matlab.mat files generated by that script to be in all participants'
%directories
analysis_dir = '/Users/erin/Desktop/Projects/Repeatability/working';
subjects = {'R02','R03','R05','R06','R07','R08','R09','R10'};

sessions = {
    {'sess1','sess2'}
    {'sess1','sess2'}
    {'sess1','sess2'}
    {'sess1','sess2'}
    {'sess1','sess2'}
    {'sess1','sess2'}
    {'sess1','sess2'}
    {'sess1','sess2'}
};

for kk = 1:length(subjects)
    theSessions = sessions{kk};
    for jj = 1:length(theSessions)
        intervals_1s(fullfile(analysis_dir,subjects{kk},theSessions{jj},'respiract'));
    end
end
