
function results = process_ET_data_bpm(inputfile)
load(inputfile) %generated by process_ET_data
buffer=1000; %to match variables saved in process_ET_data.

bh1_CO2_bpm=respiract((bh1_est_actstart):bh1_endind,4);
bh1_samptime_min_bpm=respiract(bh1_est_actstart:bh1_endind,1);
%get rid of buffers that don't look like they are part of the tasks but
%that I included to correlate to fMRI results

%sort because sometimes I have added to end of loc array to fix earlier
%breaths, need them to be in the right order to remove the buffer correctly
locs_bpm=sort(locs);
locs_bpm=locs_bpm(locs_bpm>buffer);
locs_bpm=locs_bpm(locs_bpm<(locs_bpm(end)-buffer));
%get duration of breathing = duration of task - 100 s of breath holding
bh1_dur_bpm=bh1_samptime_min_bpm(end)-bh1_samptime_min_bpm(1)-100/60;
bh1_bpm=length(locs_bpm)/bh1_dur_bpm;

bh2_CO2_bpm=respiract((bh2_est_actstart):bh2_endind,4);
bh2_samptime_min_bpm=respiract(bh2_est_actstart:bh2_endind,1);
%get rid of buffers that don't look like they are part of the tasks but
%that I included to correlate to fMRI results
locs2_bpm=sort(locs);
locs2_bpm=locs2_bpm(locs2_bpm>buffer);
locs2_bpm=locs2_bpm(locs2_bpm<(locs2_bpm(end)-buffer));
%get duration of breathing = duration of task - 100 s of breath holding
bh2_dur_bpm=bh2_samptime_min_bpm(end)-bh2_samptime_min_bpm(1)-100/60;
bh2_bpm=length(locs2_bpm)/bh2_dur_bpm;

hc1_CO2_bpm=respiract(HC1_startind:HC1_endind,4);
hc1_samptime_min_bpm=respiract(HC1_startind:HC1_endind,1);
%get rid of buffers that don't look like they are part of the tasks but
%that I included to correlate to fMRI results
locs3_bpm=sort(locs3);
locs3_bpm=locs3_bpm(locs3_bpm>buffer);
locs3_bpm=locs3_bpm(locs3_bpm<(locs3_bpm(end)-buffer));
%get duration of breathing = duration of task - 100 s of breath holding
hc1_dur_bpm=hc1_samptime_min_bpm(end)-hc1_samptime_min_bpm(1);
hc1_bpm=length(locs3_bpm)/hc1_dur_bpm;

hc2_CO2_bpm=respiract(HC2_startind:HC2_endind,4);
hc2_samptime_min_bpm=respiract(HC2_startind:HC2_endind,1);
%get rid of buffers that don't look like they are part of the tasks but
%that I included to correlate to fMRI results
locs4_bpm=sort(locs4);
locs4_bpm=locs4_bpm(locs4_bpm>buffer);
locs4_bpm=locs4_bpm(locs4_bpm<(locs4_bpm(end)-buffer));
%get duration of breathing = duration of task - 100 s of breath holding
hc2_dur_bpm=hc2_samptime_min_bpm(end)-hc2_samptime_min_bpm(1);
hc2_bpm=length(locs4_bpm)/hc2_dur_bpm;

%[hc1_bpm hc2_bpm bh1_bpm bh2_bpm]
results=sprintf("%s,%f,%f,%f,%f", inputfile, hc1_bpm, hc2_bpm, bh1_bpm, bh2_bpm);
[pathstr name ext]=fileparts(inputfile);
save(fullfile(pathstr,[name '2' ext])); %updated copy of matlab.mat
end
